### ISSUE TITLE
Crash trying to boot the latest beta in a dedicated server

### ISSUE THREAD

**Issue by vico93** [satyrnidae/wolf-armor-and-storage-legacy#190]
## Issue Description
Today i tried to run my dedicated server (using Mohist - a Forge + Spigot hybrid stack) with the latest version of this mod available on CurseForge (`WolfArmorAndStorage-1.12.2-3.8.0+beta1-SNAPSHOT-signed.jar`) and i got [this crash](https://gist.github.com/vico93/14527321cf8afc64a1a262bea8c51ac8) at startup.

## Reproduction Steps
Happens at startup when using the latest version of the mod for 1.12.2 with Mohist b294.

## Version Information
 - OS: *Windows 10 21H2 x64*
 - Java: [*Adoptium's, JRE 8 b312*](https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot)
 - Minecraft Version: *1.12.2*
 - Forge Version: *14.23.5.2860* (built-in Mohist b294)
 - Mod Version: *3.8.0+BETA1*

## Additional Context**
Issue happened also in a test server in Athernos (free minecraft hosting).

**Comment by satyrnidae** [comment]
Do you also get the same issue on a vanilla forge server?

**Comment by vico93** [comment]
> Do you also get the same issue on a vanilla forge server?

Installed the forge server jar in the folder and tried to run it, [here](https://gist.github.com/vico93/8f1f49d938d04fc931dc1653ee4e5829)'s the crash report.

**Comment by satyrnidae** [comment]
ok this wasn't actually that difficult of an issue to fix. Forgot to mark the coremod as containing a normal mod as well.  Odd that this works on singleplayer... if it does. Hotfix soon.

**Comment by satyrnidae** [comment]
Fixed, will release on github and curse soon

**Comment by vico93** [comment]
Thanks a lot for that!

**Comment by vico93** [comment]
@satyrnidae Question: I have MixinBootstrap on my modpack. What .jar should i download from latest release?

**Comment by satyrnidae** [comment]
@vico93 You can probably use either, though I haven't uploaded the no-mixin one to curseforge. Let me know if you have any issues
